### ISSUE TITLE
Odpalanie gry

### ISSUE THREAD

**Issue by JaQb249** [m4reQ/Oss-2.0#16]
Gra się nie odpala.
Wyświetla się jedynie ścieżka.

**Comment by JaQb249** [comment]
from resourceManager import ResourceManager
  File "C:\Users\jakub\Desktop\Oss-2.0-master\oss\resourceManager.py", line 6, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'launcher' is not defined
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'importlauncher' is not defined
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'launcher' is not defined
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'import_launcher' is not defined
